ALTER TABLE users DROP COLUMN IF EXISTS nip;
ALTER TABLE users DROP COLUMN IF EXISTS nomor_hp;
ALTER TABLE users DROP COLUMN IF EXISTS pangkat;
ALTER TABLE users DROP COLUMN IF EXISTS golongan;
ALTER TABLE users DROP COLUMN IF EXISTS jabatan;
ALTER TABLE users DROP COLUMN IF EXISTS tingkat_biaya;
ALTER TABLE users DROP COLUMN IF EXISTS session_id;
ALTER TABLE users DROP COLUMN IF EXISTS demo_password;
