ALTER TABLE users ADD COLUMN IF NOT EXISTS nip VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS nomor_hp VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pangkat VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS golongan VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS jabatan VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tingkat_biaya VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS session_id VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS demo_password VARCHAR(255);
