// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dalkot.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createDalkotAssignment = `-- name: CreateDalkotAssignment :one
INSERT INTO dalkot_assignments (
    id, dalkot_record_id, user_id, assignment_type, spj_cost, actual_cost, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_at, updated_at, deleted_at, dalkot_record_id, user_id, assignment_type, spj_cost, actual_cost, status, sequence_number
`

type CreateDalkotAssignmentParams struct {
	ID             uuid.UUID       `json:"id"`
	DalkotRecordID uuid.UUID       `json:"dalkot_record_id"`
	UserID         uuid.UUID       `json:"user_id"`
	AssignmentType string          `json:"assignment_type"`
	SpjCost        sql.NullFloat64 `json:"spj_cost"`
	ActualCost     sql.NullFloat64 `json:"actual_cost"`
	Status         sql.NullString  `json:"status"`
}

func (q *Queries) CreateDalkotAssignment(ctx context.Context, arg CreateDalkotAssignmentParams) (DalkotAssignment, error) {
	row := q.db.QueryRowContext(ctx, createDalkotAssignment,
		arg.ID,
		arg.DalkotRecordID,
		arg.UserID,
		arg.AssignmentType,
		arg.SpjCost,
		arg.ActualCost,
		arg.Status,
	)
	var i DalkotAssignment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DalkotRecordID,
		&i.UserID,
		&i.AssignmentType,
		&i.SpjCost,
		&i.ActualCost,
		&i.Status,
		&i.SequenceNumber,
	)
	return i, err
}

const createDalkotRecord = `-- name: CreateDalkotRecord :one
INSERT INTO dalkot_records (
    id, spd_number, execution_date, category, official, dalkot_type, activity_name, location,
    surat_tugas_number, surat_tugas_date, report_content, status, documentation_file
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, created_at, updated_at, deleted_at, spd_number, execution_date, category, official, dalkot_type, activity_name, location, surat_tugas_number, surat_tugas_date, report_content, total_spj_cost, total_actual_cost, status, documentation_file
`

type CreateDalkotRecordParams struct {
	ID                uuid.UUID             `json:"id"`
	SpdNumber         sql.NullString        `json:"spd_number"`
	ExecutionDate     time.Time             `json:"execution_date"`
	Category          string                `json:"category"`
	Official          string                `json:"official"`
	DalkotType        string                `json:"dalkot_type"`
	ActivityName      string                `json:"activity_name"`
	Location          string                `json:"location"`
	SuratTugasNumber  sql.NullString        `json:"surat_tugas_number"`
	SuratTugasDate    sql.NullTime          `json:"surat_tugas_date"`
	ReportContent     sql.NullString        `json:"report_content"`
	Status            sql.NullString        `json:"status"`
	DocumentationFile pqtype.NullRawMessage `json:"documentation_file"`
}

func (q *Queries) CreateDalkotRecord(ctx context.Context, arg CreateDalkotRecordParams) (DalkotRecord, error) {
	row := q.db.QueryRowContext(ctx, createDalkotRecord,
		arg.ID,
		arg.SpdNumber,
		arg.ExecutionDate,
		arg.Category,
		arg.Official,
		arg.DalkotType,
		arg.ActivityName,
		arg.Location,
		arg.SuratTugasNumber,
		arg.SuratTugasDate,
		arg.ReportContent,
		arg.Status,
		arg.DocumentationFile,
	)
	var i DalkotRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.ExecutionDate,
		&i.Category,
		&i.Official,
		&i.DalkotType,
		&i.ActivityName,
		&i.Location,
		&i.SuratTugasNumber,
		&i.SuratTugasDate,
		&i.ReportContent,
		&i.TotalSpjCost,
		&i.TotalActualCost,
		&i.Status,
		&i.DocumentationFile,
	)
	return i, err
}

const deleteDalkotAssignment = `-- name: DeleteDalkotAssignment :exec
UPDATE dalkot_assignments
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDalkotAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDalkotAssignment, id)
	return err
}

const deleteDalkotRecord = `-- name: DeleteDalkotRecord :exec
UPDATE dalkot_records
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDalkotRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDalkotRecord, id)
	return err
}

const getDalkotAssignmentsByRecordID = `-- name: GetDalkotAssignmentsByRecordID :many
SELECT id, created_at, updated_at, deleted_at, dalkot_record_id, user_id, assignment_type, spj_cost, actual_cost, status, sequence_number FROM dalkot_assignments
WHERE dalkot_record_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) GetDalkotAssignmentsByRecordID(ctx context.Context, dalkotRecordID uuid.UUID) ([]DalkotAssignment, error) {
	rows, err := q.db.QueryContext(ctx, getDalkotAssignmentsByRecordID, dalkotRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DalkotAssignment{}
	for rows.Next() {
		var i DalkotAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DalkotRecordID,
			&i.UserID,
			&i.AssignmentType,
			&i.SpjCost,
			&i.ActualCost,
			&i.Status,
			&i.SequenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDalkotLocations = `-- name: GetDalkotLocations :many
SELECT id, name, is_active, created_at FROM dalkot_locations
WHERE is_active = true
ORDER BY id ASC
`

func (q *Queries) GetDalkotLocations(ctx context.Context) ([]DalkotLocation, error) {
	rows, err := q.db.QueryContext(ctx, getDalkotLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DalkotLocation{}
	for rows.Next() {
		var i DalkotLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDalkotRates = `-- name: GetDalkotRates :many
SELECT id, category_name, rate_amount, created_at, updated_at FROM dalkot_rates
ORDER BY created_at ASC
`

func (q *Queries) GetDalkotRates(ctx context.Context) ([]DalkotRate, error) {
	rows, err := q.db.QueryContext(ctx, getDalkotRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DalkotRate{}
	for rows.Next() {
		var i DalkotRate
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.RateAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDalkotRecordByID = `-- name: GetDalkotRecordByID :one
SELECT id, created_at, updated_at, deleted_at, spd_number, execution_date, category, official, dalkot_type, activity_name, location, surat_tugas_number, surat_tugas_date, report_content, total_spj_cost, total_actual_cost, status, documentation_file FROM dalkot_records
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDalkotRecordByID(ctx context.Context, id uuid.UUID) (DalkotRecord, error) {
	row := q.db.QueryRowContext(ctx, getDalkotRecordByID, id)
	var i DalkotRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.ExecutionDate,
		&i.Category,
		&i.Official,
		&i.DalkotType,
		&i.ActivityName,
		&i.Location,
		&i.SuratTugasNumber,
		&i.SuratTugasDate,
		&i.ReportContent,
		&i.TotalSpjCost,
		&i.TotalActualCost,
		&i.Status,
		&i.DocumentationFile,
	)
	return i, err
}

const getDalkotRecords = `-- name: GetDalkotRecords :many
SELECT id, created_at, updated_at, deleted_at, spd_number, execution_date, category, official, dalkot_type, activity_name, location, surat_tugas_number, surat_tugas_date, report_content, total_spj_cost, total_actual_cost, status, documentation_file FROM dalkot_records
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetDalkotRecords(ctx context.Context) ([]DalkotRecord, error) {
	rows, err := q.db.QueryContext(ctx, getDalkotRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DalkotRecord{}
	for rows.Next() {
		var i DalkotRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SpdNumber,
			&i.ExecutionDate,
			&i.Category,
			&i.Official,
			&i.DalkotType,
			&i.ActivityName,
			&i.Location,
			&i.SuratTugasNumber,
			&i.SuratTugasDate,
			&i.ReportContent,
			&i.TotalSpjCost,
			&i.TotalActualCost,
			&i.Status,
			&i.DocumentationFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDalkotSpdNumber = `-- name: NextDalkotSpdNumber :one
SELECT nextval('dalkot_spd_number_seq')::int
`

func (q *Queries) NextDalkotSpdNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextDalkotSpdNumber)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateDalkotAssignment = `-- name: UpdateDalkotAssignment :one
UPDATE dalkot_assignments
SET
    assignment_type = $2,
    spj_cost = $3,
    actual_cost = $4,
    status = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, dalkot_record_id, user_id, assignment_type, spj_cost, actual_cost, status, sequence_number
`

type UpdateDalkotAssignmentParams struct {
	ID             uuid.UUID       `json:"id"`
	AssignmentType string          `json:"assignment_type"`
	SpjCost        sql.NullFloat64 `json:"spj_cost"`
	ActualCost     sql.NullFloat64 `json:"actual_cost"`
	Status         sql.NullString  `json:"status"`
}

func (q *Queries) UpdateDalkotAssignment(ctx context.Context, arg UpdateDalkotAssignmentParams) (DalkotAssignment, error) {
	row := q.db.QueryRowContext(ctx, updateDalkotAssignment,
		arg.ID,
		arg.AssignmentType,
		arg.SpjCost,
		arg.ActualCost,
		arg.Status,
	)
	var i DalkotAssignment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DalkotRecordID,
		&i.UserID,
		&i.AssignmentType,
		&i.SpjCost,
		&i.ActualCost,
		&i.Status,
		&i.SequenceNumber,
	)
	return i, err
}

const updateDalkotRecord = `-- name: UpdateDalkotRecord :one
UPDATE dalkot_records
SET
    spd_number = $2,
    execution_date = $3,
    category = $4,
    official = $5,
    dalkot_type = $6,
    activity_name = $7,
    location = $8,
    surat_tugas_number = $9,
    surat_tugas_date = $10,
    report_content = $11,
    status = $12,
    documentation_file = $13,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, spd_number, execution_date, category, official, dalkot_type, activity_name, location, surat_tugas_number, surat_tugas_date, report_content, total_spj_cost, total_actual_cost, status, documentation_file
`

type UpdateDalkotRecordParams struct {
	ID                uuid.UUID             `json:"id"`
	SpdNumber         sql.NullString        `json:"spd_number"`
	ExecutionDate     time.Time             `json:"execution_date"`
	Category          string                `json:"category"`
	Official          string                `json:"official"`
	DalkotType        string                `json:"dalkot_type"`
	ActivityName      string                `json:"activity_name"`
	Location          string                `json:"location"`
	SuratTugasNumber  sql.NullString        `json:"surat_tugas_number"`
	SuratTugasDate    sql.NullTime          `json:"surat_tugas_date"`
	ReportContent     sql.NullString        `json:"report_content"`
	Status            sql.NullString        `json:"status"`
	DocumentationFile pqtype.NullRawMessage `json:"documentation_file"`
}

func (q *Queries) UpdateDalkotRecord(ctx context.Context, arg UpdateDalkotRecordParams) (DalkotRecord, error) {
	row := q.db.QueryRowContext(ctx, updateDalkotRecord,
		arg.ID,
		arg.SpdNumber,
		arg.ExecutionDate,
		arg.Category,
		arg.Official,
		arg.DalkotType,
		arg.ActivityName,
		arg.Location,
		arg.SuratTugasNumber,
		arg.SuratTugasDate,
		arg.ReportContent,
		arg.Status,
		arg.DocumentationFile,
	)
	var i DalkotRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.ExecutionDate,
		&i.Category,
		&i.Official,
		&i.DalkotType,
		&i.ActivityName,
		&i.Location,
		&i.SuratTugasNumber,
		&i.SuratTugasDate,
		&i.ReportContent,
		&i.TotalSpjCost,
		&i.TotalActualCost,
		&i.Status,
		&i.DocumentationFile,
	)
	return i, err
}
