// Code generated by manual effort. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)


const createAccountCode = `-- name: CreateAccountCode :one
INSERT INTO account_codes (code, mak, description)
VALUES ($1, $2, $3)
RETURNING id, code, mak, description, created_at, updated_at
`

type CreateAccountCodeParams struct {
	Code        string         `json:"code"`
	Mak         string         `json:"mak"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateAccountCode(ctx context.Context, arg CreateAccountCodeParams) (AccountCode, error) {
	row := q.db.QueryRowContext(ctx, createAccountCode, arg.Code, arg.Mak, arg.Description)
	var i AccountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Mak,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountCodes = `-- name: GetAccountCodes :many
SELECT id, code, mak, description, created_at, updated_at FROM account_codes
`

func (q *Queries) GetAccountCodes(ctx context.Context) ([]AccountCode, error) {
	rows, err := q.db.QueryContext(ctx, getAccountCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountCode
	for rows.Next() {
		var i AccountCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Mak,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
