// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: gup.sql

package db

import (
	"context"
)

const getAccountCodes = `-- name: GetAccountCodes :many
SELECT id, code, mak, description, created_at, updated_at FROM account_codes
`

func (q *Queries) GetAccountCodes(ctx context.Context) ([]AccountCode, error) {
	rows, err := q.db.QueryContext(ctx, getAccountCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountCode{}
	for rows.Next() {
		var i AccountCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Mak,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
