// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: master.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProvince = `-- name: CreateProvince :one
INSERT INTO provinces (id, name, code) VALUES ($1, $2, $3) RETURNING id, created_at, updated_at, deleted_at, name, code
`

type CreateProvinceParams struct {
	ID   uuid.UUID      `json:"id"`
	Name string         `json:"name"`
	Code sql.NullString `json:"code"`
}

func (q *Queries) CreateProvince(ctx context.Context, arg CreateProvinceParams) (Province, error) {
	row := q.db.QueryRowContext(ctx, createProvince, arg.ID, arg.Name, arg.Code)
	var i Province
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Code,
	)
	return i, err
}

const createSBMRate = `-- name: CreateSBMRate :one
INSERT INTO sbm_rates (
  id, province_id, year, fullboard_rate, fullhalf_rate, outside_city_rate, inside_city_rate, diklat_rate, hotel_echelon1, hotel_echelon2, hotel_echelon3, hotel_echelon4, hotel_staff, taxi_rate
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, created_at, updated_at, deleted_at, province_id, year, fullboard_rate, fullhalf_rate, outside_city_rate, inside_city_rate, diklat_rate, hotel_echelon1, hotel_echelon2, hotel_echelon3, hotel_echelon4, hotel_staff, taxi_rate
`

type CreateSBMRateParams struct {
	ID              uuid.UUID       `json:"id"`
	ProvinceID      uuid.UUID       `json:"province_id"`
	Year            int32           `json:"year"`
	FullboardRate   sql.NullFloat64 `json:"fullboard_rate"`
	FullhalfRate    sql.NullFloat64 `json:"fullhalf_rate"`
	OutsideCityRate sql.NullFloat64 `json:"outside_city_rate"`
	InsideCityRate  sql.NullFloat64 `json:"inside_city_rate"`
	DiklatRate      sql.NullFloat64 `json:"diklat_rate"`
	HotelEchelon1   sql.NullFloat64 `json:"hotel_echelon1"`
	HotelEchelon2   sql.NullFloat64 `json:"hotel_echelon2"`
	HotelEchelon3   sql.NullFloat64 `json:"hotel_echelon3"`
	HotelEchelon4   sql.NullFloat64 `json:"hotel_echelon4"`
	HotelStaff      sql.NullFloat64 `json:"hotel_staff"`
	TaxiRate        sql.NullFloat64 `json:"taxi_rate"`
}

func (q *Queries) CreateSBMRate(ctx context.Context, arg CreateSBMRateParams) (SbmRate, error) {
	row := q.db.QueryRowContext(ctx, createSBMRate,
		arg.ID,
		arg.ProvinceID,
		arg.Year,
		arg.FullboardRate,
		arg.FullhalfRate,
		arg.OutsideCityRate,
		arg.InsideCityRate,
		arg.DiklatRate,
		arg.HotelEchelon1,
		arg.HotelEchelon2,
		arg.HotelEchelon3,
		arg.HotelEchelon4,
		arg.HotelStaff,
		arg.TaxiRate,
	)
	var i SbmRate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProvinceID,
		&i.Year,
		&i.FullboardRate,
		&i.FullhalfRate,
		&i.OutsideCityRate,
		&i.InsideCityRate,
		&i.DiklatRate,
		&i.HotelEchelon1,
		&i.HotelEchelon2,
		&i.HotelEchelon3,
		&i.HotelEchelon4,
		&i.HotelStaff,
		&i.TaxiRate,
	)
	return i, err
}

const getProvinceByCode = `-- name: GetProvinceByCode :one
SELECT id, created_at, updated_at, deleted_at, name, code FROM provinces WHERE code = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProvinceByCode(ctx context.Context, code sql.NullString) (Province, error) {
	row := q.db.QueryRowContext(ctx, getProvinceByCode, code)
	var i Province
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Code,
	)
	return i, err
}

const getProvinces = `-- name: GetProvinces :many
SELECT id, created_at, updated_at, deleted_at, name, code FROM provinces WHERE deleted_at IS NULL ORDER BY name ASC
`

func (q *Queries) GetProvinces(ctx context.Context) ([]Province, error) {
	rows, err := q.db.QueryContext(ctx, getProvinces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Province{}
	for rows.Next() {
		var i Province
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSBMRateByProvinceAndYear = `-- name: GetSBMRateByProvinceAndYear :one
SELECT id, created_at, updated_at, deleted_at, province_id, year, fullboard_rate, fullhalf_rate, outside_city_rate, inside_city_rate, diklat_rate, hotel_echelon1, hotel_echelon2, hotel_echelon3, hotel_echelon4, hotel_staff, taxi_rate FROM sbm_rates WHERE province_id = $1 AND year = $2 AND deleted_at IS NULL LIMIT 1
`

type GetSBMRateByProvinceAndYearParams struct {
	ProvinceID uuid.UUID `json:"province_id"`
	Year       int32     `json:"year"`
}

func (q *Queries) GetSBMRateByProvinceAndYear(ctx context.Context, arg GetSBMRateByProvinceAndYearParams) (SbmRate, error) {
	row := q.db.QueryRowContext(ctx, getSBMRateByProvinceAndYear, arg.ProvinceID, arg.Year)
	var i SbmRate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProvinceID,
		&i.Year,
		&i.FullboardRate,
		&i.FullhalfRate,
		&i.OutsideCityRate,
		&i.InsideCityRate,
		&i.DiklatRate,
		&i.HotelEchelon1,
		&i.HotelEchelon2,
		&i.HotelEchelon3,
		&i.HotelEchelon4,
		&i.HotelStaff,
		&i.TaxiRate,
	)
	return i, err
}

const getSBMRates = `-- name: GetSBMRates :many
SELECT id, created_at, updated_at, deleted_at, province_id, year, fullboard_rate, fullhalf_rate, outside_city_rate, inside_city_rate, diklat_rate, hotel_echelon1, hotel_echelon2, hotel_echelon3, hotel_echelon4, hotel_staff, taxi_rate FROM sbm_rates WHERE deleted_at IS NULL ORDER BY year DESC, province_id ASC
`

func (q *Queries) GetSBMRates(ctx context.Context) ([]SbmRate, error) {
	rows, err := q.db.QueryContext(ctx, getSBMRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SbmRate{}
	for rows.Next() {
		var i SbmRate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProvinceID,
			&i.Year,
			&i.FullboardRate,
			&i.FullhalfRate,
			&i.OutsideCityRate,
			&i.InsideCityRate,
			&i.DiklatRate,
			&i.HotelEchelon1,
			&i.HotelEchelon2,
			&i.HotelEchelon3,
			&i.HotelEchelon4,
			&i.HotelStaff,
			&i.TaxiRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT key, value, updated_at FROM settings WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByKey, key)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getSettings = `-- name: GetSettings :many
SELECT key, value, updated_at FROM settings
`

func (q *Queries) GetSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, getSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :one
INSERT INTO settings (key, value, updated_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = EXCLUDED.updated_at
RETURNING key, value, updated_at
`

type UpdateSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSetting, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
