// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Province struct {
	ID        uuid.UUID      `json:"id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	Name      string         `json:"name"`
	Code      sql.NullString `json:"code"`
}

type SbmRate struct {
	ID              uuid.UUID       `json:"id"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	ProvinceID      uuid.UUID       `json:"province_id"`
	Year            int32           `json:"year"`
	FullboardRate   sql.NullFloat64 `json:"fullboard_rate"`
	FullhalfRate    sql.NullFloat64 `json:"fullhalf_rate"`
	OutsideCityRate sql.NullFloat64 `json:"outside_city_rate"`
	InsideCityRate  sql.NullFloat64 `json:"inside_city_rate"`
	DiklatRate      sql.NullFloat64 `json:"diklat_rate"`
	HotelEchelon1   sql.NullFloat64 `json:"hotel_echelon1"`
	HotelEchelon2   sql.NullFloat64 `json:"hotel_echelon2"`
	HotelEchelon3   sql.NullFloat64 `json:"hotel_echelon3"`
	HotelEchelon4   sql.NullFloat64 `json:"hotel_echelon4"`
	HotelStaff      sql.NullFloat64 `json:"hotel_staff"`
	TaxiRate        sql.NullFloat64 `json:"taxi_rate"`
}

type Setting struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type TravelCost struct {
	TravelRecordID     uuid.UUID             `json:"travel_record_id"`
	TicketGo           sql.NullFloat64       `json:"ticket_go"`
	TicketBack         sql.NullFloat64       `json:"ticket_back"`
	DailyAllowanceDays sql.NullInt32         `json:"daily_allowance_days"`
	DailyAllowanceRate sql.NullFloat64       `json:"daily_allowance_rate"`
	HotelDays          sql.NullInt32         `json:"hotel_days"`
	HotelRate          sql.NullFloat64       `json:"hotel_rate"`
	LocalTransport     sql.NullFloat64       `json:"local_transport"`
	RegionalTransport  sql.NullFloat64       `json:"regional_transport"`
	TransportMode      sql.NullString        `json:"transport_mode"`
	TransportAmount    sql.NullFloat64       `json:"transport_amount"`
	OtherCost          sql.NullFloat64       `json:"other_cost"`
	OtherCostDesc      sql.NullString        `json:"other_cost_desc"`
	ReceiptFiles       pqtype.NullRawMessage `json:"receipt_files"`
	TicketGoFile       pqtype.NullRawMessage `json:"ticket_go_file"`
	TicketBackFile     pqtype.NullRawMessage `json:"ticket_back_file"`
	BoardingPassFile   pqtype.NullRawMessage `json:"boarding_pass_file"`
	HotelFile          pqtype.NullRawMessage `json:"hotel_file"`
	TransportFile      pqtype.NullRawMessage `json:"transport_file"`
	AdditionalCosts    pqtype.NullRawMessage `json:"additional_costs"`
	Details            pqtype.NullRawMessage `json:"details"`
}

type TravelLocation struct {
	ID             uuid.UUID    `json:"id"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
	TravelRecordID uuid.UUID    `json:"travel_record_id"`
	Location       string       `json:"location"`
	Province       string       `json:"province"`
	StartDate      time.Time    `json:"start_date"`
	EndDate        time.Time    `json:"end_date"`
}

type TravelRecord struct {
	ID               uuid.UUID       `json:"id"`
	CreatedAt        sql.NullTime    `json:"created_at"`
	UpdatedAt        sql.NullTime    `json:"updated_at"`
	DeletedAt        sql.NullTime    `json:"deleted_at"`
	SpdNumber        sql.NullString  `json:"spd_number"`
	EmployeeID       uuid.UUID       `json:"employee_id"`
	CreatorID        uuid.UUID       `json:"creator_id"`
	StartDate        sql.NullTime    `json:"start_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	Location         sql.NullString  `json:"location"`
	Province         sql.NullString  `json:"province"`
	Type             sql.NullString  `json:"type"`
	Purpose          sql.NullString  `json:"purpose"`
	Stakeholder      sql.NullString  `json:"stakeholder"`
	Agenda           sql.NullString  `json:"agenda"`
	Status           sql.NullString  `json:"status"`
	IsViewed         sql.NullBool    `json:"is_viewed"`
	ReportStatus     sql.NullString  `json:"report_status"`
	PaymentStatus    sql.NullString  `json:"payment_status"`
	TotalCost        sql.NullFloat64 `json:"total_cost"`
	SuratTugasPath   sql.NullString  `json:"surat_tugas_path"`
	SuratTugasNumber sql.NullString  `json:"surat_tugas_number"`
	SuratTugasDate   sql.NullTime    `json:"surat_tugas_date"`
	SequenceNumber   sql.NullInt32   `json:"sequence_number"`
}

type TravelReport struct {
	TravelRecordID uuid.UUID             `json:"travel_record_id"`
	Text           sql.NullString        `json:"text"`
	SubmittedAt    sql.NullTime          `json:"submitted_at"`
	Files          pqtype.NullRawMessage `json:"files"`
	SppdFile       pqtype.NullRawMessage `json:"sppd_file"`
	SuratTugasFile pqtype.NullRawMessage `json:"surat_tugas_file"`
	PpkName        sql.NullString        `json:"ppk_name"`
	PpkNip         sql.NullString        `json:"ppk_nip"`
	BendaharaName  sql.NullString        `json:"bendahara_name"`
	BendaharaNip   sql.NullString        `json:"bendahara_nip"`
	TanggalMerah   pqtype.NullRawMessage `json:"tanggal_merah"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Nip          sql.NullString `json:"nip"`
	NomorHp      sql.NullString `json:"nomor_hp"`
	Pangkat      sql.NullString `json:"pangkat"`
	Golongan     sql.NullString `json:"golongan"`
	Jabatan      sql.NullString `json:"jabatan"`
	TingkatBiaya sql.NullString `json:"tingkat_biaya"`
	SessionID    sql.NullString `json:"session_id"`
	DemoPassword sql.NullString `json:"demo_password"`
}
