// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProvince(ctx context.Context, arg CreateProvinceParams) (Province, error)
	CreateSBMRate(ctx context.Context, arg CreateSBMRateParams) (SbmRate, error)
	CreateTravelCost(ctx context.Context, arg CreateTravelCostParams) (TravelCost, error)
	CreateTravelLocation(ctx context.Context, arg CreateTravelLocationParams) (TravelLocation, error)
	CreateTravelRecord(ctx context.Context, arg CreateTravelRecordParams) (TravelRecord, error)
	CreateTravelReport(ctx context.Context, arg CreateTravelReportParams) (TravelReport, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTravelCost(ctx context.Context, travelRecordID uuid.UUID) error
	DeleteTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) error
	DeleteTravelRecord(ctx context.Context, id uuid.UUID) error
	DeleteTravelRecordBySpd(ctx context.Context, spdNumber sql.NullString) error
	DeleteTravelReport(ctx context.Context, travelRecordID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetLatestSpdNumber(ctx context.Context) (sql.NullString, error)
	GetOverlappingRecords(ctx context.Context, arg GetOverlappingRecordsParams) ([]TravelRecord, error)
	GetProvinceByCode(ctx context.Context, code sql.NullString) (Province, error)
	GetProvinces(ctx context.Context) ([]Province, error)
	GetSBMRateByProvinceAndYear(ctx context.Context, arg GetSBMRateByProvinceAndYearParams) (SbmRate, error)
	GetSBMRates(ctx context.Context) ([]SbmRate, error)
	GetTravelCostByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelCost, error)
	GetTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) ([]TravelLocation, error)
	GetTravelRecordByID(ctx context.Context, id uuid.UUID) (TravelRecord, error)
	GetTravelRecords(ctx context.Context, dollar_1 string) ([]TravelRecord, error)
	GetTravelReportByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelReport, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateTravelCost(ctx context.Context, arg UpdateTravelCostParams) (TravelCost, error)
	UpdateTravelRecord(ctx context.Context, arg UpdateTravelRecordParams) (TravelRecord, error)
	UpdateTravelReport(ctx context.Context, arg UpdateTravelReportParams) (TravelReport, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
