// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDalkotAssignment(ctx context.Context, arg CreateDalkotAssignmentParams) (DalkotAssignment, error)
	CreateDalkotRecord(ctx context.Context, arg CreateDalkotRecordParams) (DalkotRecord, error)
	CreateProvince(ctx context.Context, arg CreateProvinceParams) (Province, error)
	CreateSBMRate(ctx context.Context, arg CreateSBMRateParams) (SbmRate, error)
	CreateTravelCost(ctx context.Context, arg CreateTravelCostParams) (TravelCost, error)
	CreateTravelLocation(ctx context.Context, arg CreateTravelLocationParams) (TravelLocation, error)
	CreateTravelRecord(ctx context.Context, arg CreateTravelRecordParams) (TravelRecord, error)
	CreateTravelReport(ctx context.Context, arg CreateTravelReportParams) (TravelReport, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDalkotAssignment(ctx context.Context, id uuid.UUID) error
	DeleteDalkotRecord(ctx context.Context, id uuid.UUID) error
	DeleteTravelCost(ctx context.Context, travelRecordID uuid.UUID) error
	DeleteTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) error
	DeleteTravelLocationsBySpd(ctx context.Context, spdNumber sql.NullString) error
	DeleteTravelRecord(ctx context.Context, id uuid.UUID) error
	DeleteTravelRecordBySpd(ctx context.Context, spdNumber sql.NullString) error
	DeleteTravelReport(ctx context.Context, travelRecordID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAccountCodes(ctx context.Context) ([]AccountCode, error)
	GetActiveTripsCount(ctx context.Context, userID uuid.NullUUID) (int64, error)
	GetDalkotAssignmentsByRecordID(ctx context.Context, dalkotRecordID uuid.UUID) ([]DalkotAssignment, error)
	GetDalkotLocations(ctx context.Context) ([]DalkotLocation, error)
	GetDalkotRecordByID(ctx context.Context, id uuid.UUID) (DalkotRecord, error)
	GetDalkotRecords(ctx context.Context) ([]DalkotRecord, error)
	GetDashboardBudgets(ctx context.Context, userID uuid.NullUUID) ([]GetDashboardBudgetsRow, error)
	GetDashboardReportCounts(ctx context.Context, userID uuid.NullUUID) ([]GetDashboardReportCountsRow, error)
	GetDashboardStatusCounts(ctx context.Context, userID uuid.NullUUID) ([]GetDashboardStatusCountsRow, error)
	GetOverlappingRecords(ctx context.Context, arg GetOverlappingRecordsParams) ([]TravelRecord, error)
	GetPaginatedSPDs(ctx context.Context, arg GetPaginatedSPDsParams) ([]sql.NullString, error)
	GetProvinceByCode(ctx context.Context, code sql.NullString) (Province, error)
	GetProvinces(ctx context.Context) ([]Province, error)
	GetRecentRecords(ctx context.Context, userID uuid.NullUUID) ([]TravelRecord, error)
	GetRecordsBySPDs(ctx context.Context, spds []string) ([]TravelRecord, error)
	GetSBMRateByProvinceAndYear(ctx context.Context, arg GetSBMRateByProvinceAndYearParams) (SbmRate, error)
	GetSBMRates(ctx context.Context) ([]SbmRate, error)
	GetSequenceNumbers(ctx context.Context, recordIds []uuid.UUID) ([]GetSequenceNumbersRow, error)
	GetSettingByKey(ctx context.Context, key string) (Setting, error)
	GetSettings(ctx context.Context) ([]Setting, error)
	GetTotalPaginatedSPDsCount(ctx context.Context, arg GetTotalPaginatedSPDsCountParams) (int64, error)
	GetTotalTripsCount(ctx context.Context, userID uuid.NullUUID) (int64, error)
	GetTravelCostByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelCost, error)
	GetTravelCostsByRecordIDs(ctx context.Context, recordIds []uuid.UUID) ([]TravelCost, error)
	GetTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) ([]TravelLocation, error)
	GetTravelLocationsByRecordIDs(ctx context.Context, recordIds []uuid.UUID) ([]TravelLocation, error)
	GetTravelRecordByID(ctx context.Context, id uuid.UUID) (TravelRecord, error)
	GetTravelRecords(ctx context.Context, dollar_1 string) ([]TravelRecord, error)
	GetTravelReportByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelReport, error)
	GetTravelReportsByRecordIDs(ctx context.Context, recordIds []uuid.UUID) ([]TravelReport, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]User, error)
	// Returns the next unique sequence value for SPD number generation.
	// nextval() is atomic and safe under concurrent load.
	NextSpdNumber(ctx context.Context) (int64, error)
	SyncSpdSequence(ctx context.Context) error
	UpdateDalkotAssignment(ctx context.Context, arg UpdateDalkotAssignmentParams) (DalkotAssignment, error)
	UpdateDalkotRecord(ctx context.Context, arg UpdateDalkotRecordParams) (DalkotRecord, error)
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error)
	UpdateTravelCost(ctx context.Context, arg UpdateTravelCostParams) (TravelCost, error)
	UpdateTravelRecord(ctx context.Context, arg UpdateTravelRecordParams) (TravelRecord, error)
	UpdateTravelReport(ctx context.Context, arg UpdateTravelReportParams) (TravelReport, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
