// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: records.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createTravelCost = `-- name: CreateTravelCost :one
INSERT INTO travel_costs (
  travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
) RETURNING travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs
`

type CreateTravelCostParams struct {
	TravelRecordID     uuid.UUID             `json:"travel_record_id"`
	TicketGo           sql.NullFloat64       `json:"ticket_go"`
	TicketBack         sql.NullFloat64       `json:"ticket_back"`
	DailyAllowanceDays sql.NullInt32         `json:"daily_allowance_days"`
	DailyAllowanceRate sql.NullFloat64       `json:"daily_allowance_rate"`
	HotelDays          sql.NullInt32         `json:"hotel_days"`
	HotelRate          sql.NullFloat64       `json:"hotel_rate"`
	LocalTransport     sql.NullFloat64       `json:"local_transport"`
	RegionalTransport  sql.NullFloat64       `json:"regional_transport"`
	TransportMode      sql.NullString        `json:"transport_mode"`
	TransportAmount    sql.NullFloat64       `json:"transport_amount"`
	OtherCost          sql.NullFloat64       `json:"other_cost"`
	OtherCostDesc      sql.NullString        `json:"other_cost_desc"`
	ReceiptFiles       pqtype.NullRawMessage `json:"receipt_files"`
	TicketGoFile       pqtype.NullRawMessage `json:"ticket_go_file"`
	TicketBackFile     pqtype.NullRawMessage `json:"ticket_back_file"`
	BoardingPassFile   pqtype.NullRawMessage `json:"boarding_pass_file"`
	HotelFile          pqtype.NullRawMessage `json:"hotel_file"`
	TransportFile      pqtype.NullRawMessage `json:"transport_file"`
	AdditionalCosts    pqtype.NullRawMessage `json:"additional_costs"`
}

func (q *Queries) CreateTravelCost(ctx context.Context, arg CreateTravelCostParams) (TravelCost, error) {
	row := q.db.QueryRowContext(ctx, createTravelCost,
		arg.TravelRecordID,
		arg.TicketGo,
		arg.TicketBack,
		arg.DailyAllowanceDays,
		arg.DailyAllowanceRate,
		arg.HotelDays,
		arg.HotelRate,
		arg.LocalTransport,
		arg.RegionalTransport,
		arg.TransportMode,
		arg.TransportAmount,
		arg.OtherCost,
		arg.OtherCostDesc,
		arg.ReceiptFiles,
		arg.TicketGoFile,
		arg.TicketBackFile,
		arg.BoardingPassFile,
		arg.HotelFile,
		arg.TransportFile,
		arg.AdditionalCosts,
	)
	var i TravelCost
	err := row.Scan(
		&i.TravelRecordID,
		&i.TicketGo,
		&i.TicketBack,
		&i.DailyAllowanceDays,
		&i.DailyAllowanceRate,
		&i.HotelDays,
		&i.HotelRate,
		&i.LocalTransport,
		&i.RegionalTransport,
		&i.TransportMode,
		&i.TransportAmount,
		&i.OtherCost,
		&i.OtherCostDesc,
		&i.ReceiptFiles,
		&i.TicketGoFile,
		&i.TicketBackFile,
		&i.BoardingPassFile,
		&i.HotelFile,
		&i.TransportFile,
		&i.AdditionalCosts,
	)
	return i, err
}

const createTravelLocation = `-- name: CreateTravelLocation :one
INSERT INTO travel_locations (
  id, travel_record_id, location, province, start_date, end_date
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, created_at, updated_at, deleted_at, travel_record_id, location, province, start_date, end_date
`

type CreateTravelLocationParams struct {
	ID             uuid.UUID `json:"id"`
	TravelRecordID uuid.UUID `json:"travel_record_id"`
	Location       string    `json:"location"`
	Province       string    `json:"province"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
}

func (q *Queries) CreateTravelLocation(ctx context.Context, arg CreateTravelLocationParams) (TravelLocation, error) {
	row := q.db.QueryRowContext(ctx, createTravelLocation,
		arg.ID,
		arg.TravelRecordID,
		arg.Location,
		arg.Province,
		arg.StartDate,
		arg.EndDate,
	)
	var i TravelLocation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TravelRecordID,
		&i.Location,
		&i.Province,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const createTravelRecord = `-- name: CreateTravelRecord :one
INSERT INTO travel_records (
  id, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, report_status, payment_status, total_cost, surat_tugas_path, surat_tugas_number
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, report_status, payment_status, total_cost, surat_tugas_path, surat_tugas_number
`

type CreateTravelRecordParams struct {
	ID               uuid.UUID       `json:"id"`
	SpdNumber        sql.NullString  `json:"spd_number"`
	EmployeeID       uuid.UUID       `json:"employee_id"`
	CreatorID        uuid.UUID       `json:"creator_id"`
	StartDate        sql.NullTime    `json:"start_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	Location         sql.NullString  `json:"location"`
	Province         sql.NullString  `json:"province"`
	Type             sql.NullString  `json:"type"`
	Purpose          sql.NullString  `json:"purpose"`
	Stakeholder      sql.NullString  `json:"stakeholder"`
	Agenda           sql.NullString  `json:"agenda"`
	Status           sql.NullString  `json:"status"`
	IsViewed         sql.NullBool    `json:"is_viewed"`
	ReportStatus     sql.NullString  `json:"report_status"`
	PaymentStatus    sql.NullString  `json:"payment_status"`
	TotalCost        sql.NullFloat64 `json:"total_cost"`
	SuratTugasPath   sql.NullString  `json:"surat_tugas_path"`
	SuratTugasNumber sql.NullString  `json:"surat_tugas_number"`
}

func (q *Queries) CreateTravelRecord(ctx context.Context, arg CreateTravelRecordParams) (TravelRecord, error) {
	row := q.db.QueryRowContext(ctx, createTravelRecord,
		arg.ID,
		arg.SpdNumber,
		arg.EmployeeID,
		arg.CreatorID,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.Province,
		arg.Type,
		arg.Purpose,
		arg.Stakeholder,
		arg.Agenda,
		arg.Status,
		arg.IsViewed,
		arg.ReportStatus,
		arg.PaymentStatus,
		arg.TotalCost,
		arg.SuratTugasPath,
		arg.SuratTugasNumber,
	)
	var i TravelRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.EmployeeID,
		&i.CreatorID,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.Province,
		&i.Type,
		&i.Purpose,
		&i.Stakeholder,
		&i.Agenda,
		&i.Status,
		&i.IsViewed,
		&i.ReportStatus,
		&i.PaymentStatus,
		&i.TotalCost,
		&i.SuratTugasPath,
		&i.SuratTugasNumber,
	)
	return i, err
}

const createTravelReport = `-- name: CreateTravelReport :one
INSERT INTO travel_reports (
  travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file
`

type CreateTravelReportParams struct {
	TravelRecordID uuid.UUID             `json:"travel_record_id"`
	Text           sql.NullString        `json:"text"`
	SubmittedAt    sql.NullTime          `json:"submitted_at"`
	Files          pqtype.NullRawMessage `json:"files"`
	SppdFile       pqtype.NullRawMessage `json:"sppd_file"`
	SuratTugasFile pqtype.NullRawMessage `json:"surat_tugas_file"`
}

func (q *Queries) CreateTravelReport(ctx context.Context, arg CreateTravelReportParams) (TravelReport, error) {
	row := q.db.QueryRowContext(ctx, createTravelReport,
		arg.TravelRecordID,
		arg.Text,
		arg.SubmittedAt,
		arg.Files,
		arg.SppdFile,
		arg.SuratTugasFile,
	)
	var i TravelReport
	err := row.Scan(
		&i.TravelRecordID,
		&i.Text,
		&i.SubmittedAt,
		&i.Files,
		&i.SppdFile,
		&i.SuratTugasFile,
	)
	return i, err
}

const deleteTravelCost = `-- name: DeleteTravelCost :exec
DELETE FROM travel_costs WHERE travel_record_id = $1
`

func (q *Queries) DeleteTravelCost(ctx context.Context, travelRecordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelCost, travelRecordID)
	return err
}

const deleteTravelLocationsByRecordID = `-- name: DeleteTravelLocationsByRecordID :exec
UPDATE travel_locations SET deleted_at = CURRENT_TIMESTAMP WHERE travel_record_id = $1
`

func (q *Queries) DeleteTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelLocationsByRecordID, travelRecordID)
	return err
}

const deleteTravelRecord = `-- name: DeleteTravelRecord :exec
UPDATE travel_records SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) DeleteTravelRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelRecord, id)
	return err
}

const deleteTravelReport = `-- name: DeleteTravelReport :exec
DELETE FROM travel_reports WHERE travel_record_id = $1
`

func (q *Queries) DeleteTravelReport(ctx context.Context, travelRecordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelReport, travelRecordID)
	return err
}

const getOverlappingRecords = `-- name: GetOverlappingRecords :many
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, report_status, payment_status, total_cost, surat_tugas_path, surat_tugas_number FROM travel_records 
WHERE employee_id = $1 
  AND start_date <= $2 
  AND end_date >= $3 
  AND status != 'Rejected'
  AND deleted_at IS NULL
`

type GetOverlappingRecordsParams struct {
	EmployeeID uuid.UUID    `json:"employee_id"`
	StartDate  sql.NullTime `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
}

func (q *Queries) GetOverlappingRecords(ctx context.Context, arg GetOverlappingRecordsParams) ([]TravelRecord, error) {
	rows, err := q.db.QueryContext(ctx, getOverlappingRecords, arg.EmployeeID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelRecord{}
	for rows.Next() {
		var i TravelRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SpdNumber,
			&i.EmployeeID,
			&i.CreatorID,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.Province,
			&i.Type,
			&i.Purpose,
			&i.Stakeholder,
			&i.Agenda,
			&i.Status,
			&i.IsViewed,
			&i.ReportStatus,
			&i.PaymentStatus,
			&i.TotalCost,
			&i.SuratTugasPath,
			&i.SuratTugasNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelCostByRecordID = `-- name: GetTravelCostByRecordID :one
SELECT travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs FROM travel_costs WHERE travel_record_id = $1 LIMIT 1
`

func (q *Queries) GetTravelCostByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelCost, error) {
	row := q.db.QueryRowContext(ctx, getTravelCostByRecordID, travelRecordID)
	var i TravelCost
	err := row.Scan(
		&i.TravelRecordID,
		&i.TicketGo,
		&i.TicketBack,
		&i.DailyAllowanceDays,
		&i.DailyAllowanceRate,
		&i.HotelDays,
		&i.HotelRate,
		&i.LocalTransport,
		&i.RegionalTransport,
		&i.TransportMode,
		&i.TransportAmount,
		&i.OtherCost,
		&i.OtherCostDesc,
		&i.ReceiptFiles,
		&i.TicketGoFile,
		&i.TicketBackFile,
		&i.BoardingPassFile,
		&i.HotelFile,
		&i.TransportFile,
		&i.AdditionalCosts,
	)
	return i, err
}

const getTravelLocationsByRecordID = `-- name: GetTravelLocationsByRecordID :many
SELECT id, created_at, updated_at, deleted_at, travel_record_id, location, province, start_date, end_date FROM travel_locations WHERE travel_record_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) ([]TravelLocation, error) {
	rows, err := q.db.QueryContext(ctx, getTravelLocationsByRecordID, travelRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelLocation{}
	for rows.Next() {
		var i TravelLocation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TravelRecordID,
			&i.Location,
			&i.Province,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelRecordByID = `-- name: GetTravelRecordByID :one
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, report_status, payment_status, total_cost, surat_tugas_path, surat_tugas_number FROM travel_records WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTravelRecordByID(ctx context.Context, id uuid.UUID) (TravelRecord, error) {
	row := q.db.QueryRowContext(ctx, getTravelRecordByID, id)
	var i TravelRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.EmployeeID,
		&i.CreatorID,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.Province,
		&i.Type,
		&i.Purpose,
		&i.Stakeholder,
		&i.Agenda,
		&i.Status,
		&i.IsViewed,
		&i.ReportStatus,
		&i.PaymentStatus,
		&i.TotalCost,
		&i.SuratTugasPath,
		&i.SuratTugasNumber,
	)
	return i, err
}

const getTravelRecords = `-- name: GetTravelRecords :many
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, report_status, payment_status, total_cost, surat_tugas_path, surat_tugas_number FROM travel_records
WHERE deleted_at IS NULL
  AND (NULLIF($1::text, '') IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT 1000
`

func (q *Queries) GetTravelRecords(ctx context.Context, dollar_1 string) ([]TravelRecord, error) {
	rows, err := q.db.QueryContext(ctx, getTravelRecords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelRecord{}
	for rows.Next() {
		var i TravelRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SpdNumber,
			&i.EmployeeID,
			&i.CreatorID,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.Province,
			&i.Type,
			&i.Purpose,
			&i.Stakeholder,
			&i.Agenda,
			&i.Status,
			&i.IsViewed,
			&i.ReportStatus,
			&i.PaymentStatus,
			&i.TotalCost,
			&i.SuratTugasPath,
			&i.SuratTugasNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelReportByRecordID = `-- name: GetTravelReportByRecordID :one
SELECT travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file FROM travel_reports WHERE travel_record_id = $1 LIMIT 1
`

func (q *Queries) GetTravelReportByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelReport, error) {
	row := q.db.QueryRowContext(ctx, getTravelReportByRecordID, travelRecordID)
	var i TravelReport
	err := row.Scan(
		&i.TravelRecordID,
		&i.Text,
		&i.SubmittedAt,
		&i.Files,
		&i.SppdFile,
		&i.SuratTugasFile,
	)
	return i, err
}

const updateTravelCost = `-- name: UpdateTravelCost :one
UPDATE travel_costs SET
  ticket_go = $2, ticket_back = $3, daily_allowance_days = $4, daily_allowance_rate = $5, hotel_days = $6, hotel_rate = $7, local_transport = $8, regional_transport = $9, transport_mode = $10, transport_amount = $11, other_cost = $12, other_cost_desc = $13, receipt_files = $14, ticket_go_file = $15, ticket_back_file = $16, boarding_pass_file = $17, hotel_file = $18, transport_file = $19, additional_costs = $20
WHERE travel_record_id = $1
RETURNING travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs
`

type UpdateTravelCostParams struct {
	TravelRecordID     uuid.UUID             `json:"travel_record_id"`
	TicketGo           sql.NullFloat64       `json:"ticket_go"`
	TicketBack         sql.NullFloat64       `json:"ticket_back"`
	DailyAllowanceDays sql.NullInt32         `json:"daily_allowance_days"`
	DailyAllowanceRate sql.NullFloat64       `json:"daily_allowance_rate"`
	HotelDays          sql.NullInt32         `json:"hotel_days"`
	HotelRate          sql.NullFloat64       `json:"hotel_rate"`
	LocalTransport     sql.NullFloat64       `json:"local_transport"`
	RegionalTransport  sql.NullFloat64       `json:"regional_transport"`
	TransportMode      sql.NullString        `json:"transport_mode"`
	TransportAmount    sql.NullFloat64       `json:"transport_amount"`
	OtherCost          sql.NullFloat64       `json:"other_cost"`
	OtherCostDesc      sql.NullString        `json:"other_cost_desc"`
	ReceiptFiles       pqtype.NullRawMessage `json:"receipt_files"`
	TicketGoFile       pqtype.NullRawMessage `json:"ticket_go_file"`
	TicketBackFile     pqtype.NullRawMessage `json:"ticket_back_file"`
	BoardingPassFile   pqtype.NullRawMessage `json:"boarding_pass_file"`
	HotelFile          pqtype.NullRawMessage `json:"hotel_file"`
	TransportFile      pqtype.NullRawMessage `json:"transport_file"`
	AdditionalCosts    pqtype.NullRawMessage `json:"additional_costs"`
}

func (q *Queries) UpdateTravelCost(ctx context.Context, arg UpdateTravelCostParams) (TravelCost, error) {
	row := q.db.QueryRowContext(ctx, updateTravelCost,
		arg.TravelRecordID,
		arg.TicketGo,
		arg.TicketBack,
		arg.DailyAllowanceDays,
		arg.DailyAllowanceRate,
		arg.HotelDays,
		arg.HotelRate,
		arg.LocalTransport,
		arg.RegionalTransport,
		arg.TransportMode,
		arg.TransportAmount,
		arg.OtherCost,
		arg.OtherCostDesc,
		arg.ReceiptFiles,
		arg.TicketGoFile,
		arg.TicketBackFile,
		arg.BoardingPassFile,
		arg.HotelFile,
		arg.TransportFile,
		arg.AdditionalCosts,
	)
	var i TravelCost
	err := row.Scan(
		&i.TravelRecordID,
		&i.TicketGo,
		&i.TicketBack,
		&i.DailyAllowanceDays,
		&i.DailyAllowanceRate,
		&i.HotelDays,
		&i.HotelRate,
		&i.LocalTransport,
		&i.RegionalTransport,
		&i.TransportMode,
		&i.TransportAmount,
		&i.OtherCost,
		&i.OtherCostDesc,
		&i.ReceiptFiles,
		&i.TicketGoFile,
		&i.TicketBackFile,
		&i.BoardingPassFile,
		&i.HotelFile,
		&i.TransportFile,
		&i.AdditionalCosts,
	)
	return i, err
}

const updateTravelRecord = `-- name: UpdateTravelRecord :one
UPDATE travel_records SET
  spd_number = $2,
  employee_id = $3,
  creator_id = $4,
  start_date = $5,
  end_date = $6,
  location = $7,
  province = $8,
  type = $9,
  purpose = $10,
  stakeholder = $11,
  agenda = $12,
  status = $13,
  is_viewed = $14,
  report_status = $15,
  payment_status = $16,
  total_cost = $17,
  surat_tugas_path = $18,
  surat_tugas_number = $19,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, report_status, payment_status, total_cost, surat_tugas_path, surat_tugas_number
`

type UpdateTravelRecordParams struct {
	ID               uuid.UUID       `json:"id"`
	SpdNumber        sql.NullString  `json:"spd_number"`
	EmployeeID       uuid.UUID       `json:"employee_id"`
	CreatorID        uuid.UUID       `json:"creator_id"`
	StartDate        sql.NullTime    `json:"start_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	Location         sql.NullString  `json:"location"`
	Province         sql.NullString  `json:"province"`
	Type             sql.NullString  `json:"type"`
	Purpose          sql.NullString  `json:"purpose"`
	Stakeholder      sql.NullString  `json:"stakeholder"`
	Agenda           sql.NullString  `json:"agenda"`
	Status           sql.NullString  `json:"status"`
	IsViewed         sql.NullBool    `json:"is_viewed"`
	ReportStatus     sql.NullString  `json:"report_status"`
	PaymentStatus    sql.NullString  `json:"payment_status"`
	TotalCost        sql.NullFloat64 `json:"total_cost"`
	SuratTugasPath   sql.NullString  `json:"surat_tugas_path"`
	SuratTugasNumber sql.NullString  `json:"surat_tugas_number"`
}

func (q *Queries) UpdateTravelRecord(ctx context.Context, arg UpdateTravelRecordParams) (TravelRecord, error) {
	row := q.db.QueryRowContext(ctx, updateTravelRecord,
		arg.ID,
		arg.SpdNumber,
		arg.EmployeeID,
		arg.CreatorID,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.Province,
		arg.Type,
		arg.Purpose,
		arg.Stakeholder,
		arg.Agenda,
		arg.Status,
		arg.IsViewed,
		arg.ReportStatus,
		arg.PaymentStatus,
		arg.TotalCost,
		arg.SuratTugasPath,
		arg.SuratTugasNumber,
	)
	var i TravelRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.EmployeeID,
		&i.CreatorID,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.Province,
		&i.Type,
		&i.Purpose,
		&i.Stakeholder,
		&i.Agenda,
		&i.Status,
		&i.IsViewed,
		&i.ReportStatus,
		&i.PaymentStatus,
		&i.TotalCost,
		&i.SuratTugasPath,
		&i.SuratTugasNumber,
	)
	return i, err
}

const updateTravelReport = `-- name: UpdateTravelReport :one
UPDATE travel_reports SET
  text = $2, submitted_at = $3, files = $4, sppd_file = $5, surat_tugas_file = $6
WHERE travel_record_id = $1
RETURNING travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file
`

type UpdateTravelReportParams struct {
	TravelRecordID uuid.UUID             `json:"travel_record_id"`
	Text           sql.NullString        `json:"text"`
	SubmittedAt    sql.NullTime          `json:"submitted_at"`
	Files          pqtype.NullRawMessage `json:"files"`
	SppdFile       pqtype.NullRawMessage `json:"sppd_file"`
	SuratTugasFile pqtype.NullRawMessage `json:"surat_tugas_file"`
}

func (q *Queries) UpdateTravelReport(ctx context.Context, arg UpdateTravelReportParams) (TravelReport, error) {
	row := q.db.QueryRowContext(ctx, updateTravelReport,
		arg.TravelRecordID,
		arg.Text,
		arg.SubmittedAt,
		arg.Files,
		arg.SppdFile,
		arg.SuratTugasFile,
	)
	var i TravelReport
	err := row.Scan(
		&i.TravelRecordID,
		&i.Text,
		&i.SubmittedAt,
		&i.Files,
		&i.SppdFile,
		&i.SuratTugasFile,
	)
	return i, err
}
