// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: records.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createTravelCost = `-- name: CreateTravelCost :one
INSERT INTO travel_costs (
  travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs, details
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
) RETURNING travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs, details
`

type CreateTravelCostParams struct {
	TravelRecordID     uuid.UUID             `json:"travel_record_id"`
	TicketGo           sql.NullFloat64       `json:"ticket_go"`
	TicketBack         sql.NullFloat64       `json:"ticket_back"`
	DailyAllowanceDays sql.NullInt32         `json:"daily_allowance_days"`
	DailyAllowanceRate sql.NullFloat64       `json:"daily_allowance_rate"`
	HotelDays          sql.NullInt32         `json:"hotel_days"`
	HotelRate          sql.NullFloat64       `json:"hotel_rate"`
	LocalTransport     sql.NullFloat64       `json:"local_transport"`
	RegionalTransport  sql.NullFloat64       `json:"regional_transport"`
	TransportMode      sql.NullString        `json:"transport_mode"`
	TransportAmount    sql.NullFloat64       `json:"transport_amount"`
	OtherCost          sql.NullFloat64       `json:"other_cost"`
	OtherCostDesc      sql.NullString        `json:"other_cost_desc"`
	ReceiptFiles       pqtype.NullRawMessage `json:"receipt_files"`
	TicketGoFile       pqtype.NullRawMessage `json:"ticket_go_file"`
	TicketBackFile     pqtype.NullRawMessage `json:"ticket_back_file"`
	BoardingPassFile   pqtype.NullRawMessage `json:"boarding_pass_file"`
	HotelFile          pqtype.NullRawMessage `json:"hotel_file"`
	TransportFile      pqtype.NullRawMessage `json:"transport_file"`
	AdditionalCosts    pqtype.NullRawMessage `json:"additional_costs"`
	Details            pqtype.NullRawMessage `json:"details"`
}

func (q *Queries) CreateTravelCost(ctx context.Context, arg CreateTravelCostParams) (TravelCost, error) {
	row := q.db.QueryRowContext(ctx, createTravelCost,
		arg.TravelRecordID,
		arg.TicketGo,
		arg.TicketBack,
		arg.DailyAllowanceDays,
		arg.DailyAllowanceRate,
		arg.HotelDays,
		arg.HotelRate,
		arg.LocalTransport,
		arg.RegionalTransport,
		arg.TransportMode,
		arg.TransportAmount,
		arg.OtherCost,
		arg.OtherCostDesc,
		arg.ReceiptFiles,
		arg.TicketGoFile,
		arg.TicketBackFile,
		arg.BoardingPassFile,
		arg.HotelFile,
		arg.TransportFile,
		arg.AdditionalCosts,
		arg.Details,
	)
	var i TravelCost
	err := row.Scan(
		&i.TravelRecordID,
		&i.TicketGo,
		&i.TicketBack,
		&i.DailyAllowanceDays,
		&i.DailyAllowanceRate,
		&i.HotelDays,
		&i.HotelRate,
		&i.LocalTransport,
		&i.RegionalTransport,
		&i.TransportMode,
		&i.TransportAmount,
		&i.OtherCost,
		&i.OtherCostDesc,
		&i.ReceiptFiles,
		&i.TicketGoFile,
		&i.TicketBackFile,
		&i.BoardingPassFile,
		&i.HotelFile,
		&i.TransportFile,
		&i.AdditionalCosts,
		&i.Details,
	)
	return i, err
}

const createTravelLocation = `-- name: CreateTravelLocation :one
INSERT INTO travel_locations (
  id, travel_record_id, location, province, start_date, end_date
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, created_at, updated_at, deleted_at, travel_record_id, location, province, start_date, end_date
`

type CreateTravelLocationParams struct {
	ID             uuid.UUID `json:"id"`
	TravelRecordID uuid.UUID `json:"travel_record_id"`
	Location       string    `json:"location"`
	Province       string    `json:"province"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
}

func (q *Queries) CreateTravelLocation(ctx context.Context, arg CreateTravelLocationParams) (TravelLocation, error) {
	row := q.db.QueryRowContext(ctx, createTravelLocation,
		arg.ID,
		arg.TravelRecordID,
		arg.Location,
		arg.Province,
		arg.StartDate,
		arg.EndDate,
	)
	var i TravelLocation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TravelRecordID,
		&i.Location,
		&i.Province,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const createTravelRecord = `-- name: CreateTravelRecord :one
INSERT INTO travel_records (
  id, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date, sequence_number
`

type CreateTravelRecordParams struct {
	ID               uuid.UUID       `json:"id"`
	SpdNumber        sql.NullString  `json:"spd_number"`
	EmployeeID       uuid.UUID       `json:"employee_id"`
	CreatorID        uuid.UUID       `json:"creator_id"`
	StartDate        sql.NullTime    `json:"start_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	Location         sql.NullString  `json:"location"`
	Province         sql.NullString  `json:"province"`
	Type             sql.NullString  `json:"type"`
	Purpose          sql.NullString  `json:"purpose"`
	Stakeholder      sql.NullString  `json:"stakeholder"`
	Agenda           sql.NullString  `json:"agenda"`
	Status           sql.NullString  `json:"status"`
	IsViewed         sql.NullBool    `json:"is_viewed"`
	TotalCost        sql.NullFloat64 `json:"total_cost"`
	SuratTugasPath   sql.NullString  `json:"surat_tugas_path"`
	SuratTugasNumber sql.NullString  `json:"surat_tugas_number"`
	SuratTugasDate   sql.NullTime    `json:"surat_tugas_date"`
}

func (q *Queries) CreateTravelRecord(ctx context.Context, arg CreateTravelRecordParams) (TravelRecord, error) {
	row := q.db.QueryRowContext(ctx, createTravelRecord,
		arg.ID,
		arg.SpdNumber,
		arg.EmployeeID,
		arg.CreatorID,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.Province,
		arg.Type,
		arg.Purpose,
		arg.Stakeholder,
		arg.Agenda,
		arg.Status,
		arg.IsViewed,
		arg.TotalCost,
		arg.SuratTugasPath,
		arg.SuratTugasNumber,
		arg.SuratTugasDate,
	)
	var i TravelRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.EmployeeID,
		&i.CreatorID,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.Province,
		&i.Type,
		&i.Purpose,
		&i.Stakeholder,
		&i.Agenda,
		&i.Status,
		&i.IsViewed,
		&i.TotalCost,
		&i.SuratTugasPath,
		&i.SuratTugasNumber,
		&i.SuratTugasDate,
		&i.SequenceNumber,
	)
	return i, err
}

const createTravelReport = `-- name: CreateTravelReport :one
INSERT INTO travel_reports (
  travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file, ppk_name, ppk_nip, bendahara_name, bendahara_nip, tanggal_merah
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file, ppk_name, ppk_nip, bendahara_name, bendahara_nip, tanggal_merah
`

type CreateTravelReportParams struct {
	TravelRecordID uuid.UUID             `json:"travel_record_id"`
	Text           sql.NullString        `json:"text"`
	SubmittedAt    sql.NullTime          `json:"submitted_at"`
	Files          pqtype.NullRawMessage `json:"files"`
	SppdFile       pqtype.NullRawMessage `json:"sppd_file"`
	SuratTugasFile pqtype.NullRawMessage `json:"surat_tugas_file"`
	PpkName        sql.NullString        `json:"ppk_name"`
	PpkNip         sql.NullString        `json:"ppk_nip"`
	BendaharaName  sql.NullString        `json:"bendahara_name"`
	BendaharaNip   sql.NullString        `json:"bendahara_nip"`
	TanggalMerah   pqtype.NullRawMessage `json:"tanggal_merah"`
}

func (q *Queries) CreateTravelReport(ctx context.Context, arg CreateTravelReportParams) (TravelReport, error) {
	row := q.db.QueryRowContext(ctx, createTravelReport,
		arg.TravelRecordID,
		arg.Text,
		arg.SubmittedAt,
		arg.Files,
		arg.SppdFile,
		arg.SuratTugasFile,
		arg.PpkName,
		arg.PpkNip,
		arg.BendaharaName,
		arg.BendaharaNip,
		arg.TanggalMerah,
	)
	var i TravelReport
	err := row.Scan(
		&i.TravelRecordID,
		&i.Text,
		&i.SubmittedAt,
		&i.Files,
		&i.SppdFile,
		&i.SuratTugasFile,
		&i.PpkName,
		&i.PpkNip,
		&i.BendaharaName,
		&i.BendaharaNip,
		&i.TanggalMerah,
	)
	return i, err
}

const deleteTravelCost = `-- name: DeleteTravelCost :exec
DELETE FROM travel_costs WHERE travel_record_id = $1
`

func (q *Queries) DeleteTravelCost(ctx context.Context, travelRecordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelCost, travelRecordID)
	return err
}

const deleteTravelLocationsByRecordID = `-- name: DeleteTravelLocationsByRecordID :exec
DELETE FROM travel_locations WHERE travel_record_id = $1
`

func (q *Queries) DeleteTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelLocationsByRecordID, travelRecordID)
	return err
}

const deleteTravelLocationsBySpd = `-- name: DeleteTravelLocationsBySpd :exec
DELETE FROM travel_locations
WHERE travel_record_id IN (SELECT id FROM travel_records WHERE spd_number = $1)
`

func (q *Queries) DeleteTravelLocationsBySpd(ctx context.Context, spdNumber sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTravelLocationsBySpd, spdNumber)
	return err
}

const deleteTravelRecord = `-- name: DeleteTravelRecord :exec
DELETE FROM travel_records WHERE id = $1
`

func (q *Queries) DeleteTravelRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelRecord, id)
	return err
}

const deleteTravelRecordBySpd = `-- name: DeleteTravelRecordBySpd :exec
DELETE FROM travel_records WHERE spd_number = $1
`

func (q *Queries) DeleteTravelRecordBySpd(ctx context.Context, spdNumber sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTravelRecordBySpd, spdNumber)
	return err
}

const deleteTravelReport = `-- name: DeleteTravelReport :exec
DELETE FROM travel_reports WHERE travel_record_id = $1
`

func (q *Queries) DeleteTravelReport(ctx context.Context, travelRecordID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTravelReport, travelRecordID)
	return err
}

const getActiveTripsCount = `-- name: GetActiveTripsCount :one
SELECT COUNT(*) 
FROM travel_records 
WHERE deleted_at IS NULL 
  AND status IN ('Approved', 'Submitted', 'Assigned', 'Draft')
  AND start_date <= CURRENT_TIMESTAMP 
  AND end_date >= CURRENT_TIMESTAMP
  AND (NULLIF($1::uuid, NULL) IS NULL OR employee_id = $1 OR creator_id = $1)
`

func (q *Queries) GetActiveTripsCount(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveTripsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDashboardBudgets = `-- name: GetDashboardBudgets :many
SELECT 
  EXTRACT(YEAR FROM COALESCE(start_date, created_at))::INT as year,
  EXTRACT(MONTH FROM COALESCE(start_date, created_at))::INT as month,
  SUM(total_cost)::FLOAT8 as total
FROM travel_records
WHERE deleted_at IS NULL
  AND (NULLIF($1::uuid, NULL) IS NULL OR employee_id = $1 OR creator_id = $1)
GROUP BY year, month
ORDER BY year DESC, month DESC
`

type GetDashboardBudgetsRow struct {
	Year  int32   `json:"year"`
	Month int32   `json:"month"`
	Total float64 `json:"total"`
}

func (q *Queries) GetDashboardBudgets(ctx context.Context, userID uuid.NullUUID) ([]GetDashboardBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDashboardBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardBudgetsRow{}
	for rows.Next() {
		var i GetDashboardBudgetsRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStatusCounts = `-- name: GetDashboardStatusCounts :many
SELECT status, COUNT(*) as count 
FROM travel_records 
WHERE deleted_at IS NULL
  AND (NULLIF($1::uuid, NULL) IS NULL OR employee_id = $1 OR creator_id = $1)
GROUP BY status
`

type GetDashboardStatusCountsRow struct {
	Status sql.NullString `json:"status"`
	Count  int64          `json:"count"`
}

func (q *Queries) GetDashboardStatusCounts(ctx context.Context, userID uuid.NullUUID) ([]GetDashboardStatusCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDashboardStatusCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardStatusCountsRow{}
	for rows.Next() {
		var i GetDashboardStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverlappingRecords = `-- name: GetOverlappingRecords :many
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date, sequence_number FROM travel_records 
WHERE employee_id = $1 
  AND start_date <= $2
  AND end_date >= $3
  AND status != 'Rejected'
  AND deleted_at IS NULL
`

type GetOverlappingRecordsParams struct {
	EmployeeID   uuid.UUID    `json:"employee_id"`
	NewEndDate   sql.NullTime `json:"new_end_date"`
	NewStartDate sql.NullTime `json:"new_start_date"`
}

func (q *Queries) GetOverlappingRecords(ctx context.Context, arg GetOverlappingRecordsParams) ([]TravelRecord, error) {
	rows, err := q.db.QueryContext(ctx, getOverlappingRecords, arg.EmployeeID, arg.NewEndDate, arg.NewStartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelRecord{}
	for rows.Next() {
		var i TravelRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SpdNumber,
			&i.EmployeeID,
			&i.CreatorID,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.Province,
			&i.Type,
			&i.Purpose,
			&i.Stakeholder,
			&i.Agenda,
			&i.Status,
			&i.IsViewed,
			&i.TotalCost,
			&i.SuratTugasPath,
			&i.SuratTugasNumber,
			&i.SuratTugasDate,
			&i.SequenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedSPDs = `-- name: GetPaginatedSPDs :many
SELECT travel_records.spd_number
FROM travel_records
LEFT JOIN users ON travel_records.employee_id = users.id
WHERE travel_records.deleted_at IS NULL
  AND (NULLIF($1::text, '') IS NULL OR travel_records.status = $1)
  AND (
    NULLIF($2::text, '') IS NULL
    OR travel_records.spd_number ILIKE '%' || $2 || '%'
    OR travel_records.location ILIKE '%' || $2 || '%'
    OR users.name ILIKE '%' || $2 || '%'
  )
  AND (NULLIF($3::timestamp, NULL) IS NULL OR travel_records.start_date >= $3)
  AND (NULLIF($4::timestamp, NULL) IS NULL OR travel_records.start_date <= $4)
  AND (NULLIF($5::uuid, NULL) IS NULL OR travel_records.employee_id = $5 OR travel_records.creator_id = $5)
  AND (NULLIF($6::text, '') IS NULL OR travel_records.spd_number < $6)
GROUP BY travel_records.spd_number
ORDER BY travel_records.spd_number DESC
LIMIT $7
`

type GetPaginatedSPDsParams struct {
	Status    sql.NullString `json:"status"`
	Search    sql.NullString `json:"search"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	UserID    uuid.NullUUID  `json:"user_id"`
	Cursor    sql.NullString `json:"cursor"`
	Limit     int32          `json:"limit"`
}

func (q *Queries) GetPaginatedSPDs(ctx context.Context, arg GetPaginatedSPDsParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getPaginatedSPDs,
		arg.Status,
		arg.Search,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var spd_number sql.NullString
		if err := rows.Scan(&spd_number); err != nil {
			return nil, err
		}
		items = append(items, spd_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentRecords = `-- name: GetRecentRecords :many
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date, sequence_number FROM travel_records 
WHERE deleted_at IS NULL 
  AND (NULLIF($1::uuid, NULL) IS NULL OR employee_id = $1 OR creator_id = $1)
ORDER BY created_at DESC, id ASC 
LIMIT 5
`

func (q *Queries) GetRecentRecords(ctx context.Context, userID uuid.NullUUID) ([]TravelRecord, error) {
	rows, err := q.db.QueryContext(ctx, getRecentRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelRecord{}
	for rows.Next() {
		var i TravelRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SpdNumber,
			&i.EmployeeID,
			&i.CreatorID,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.Province,
			&i.Type,
			&i.Purpose,
			&i.Stakeholder,
			&i.Agenda,
			&i.Status,
			&i.IsViewed,
			&i.TotalCost,
			&i.SuratTugasPath,
			&i.SuratTugasNumber,
			&i.SuratTugasDate,
			&i.SequenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordsBySPDs = `-- name: GetRecordsBySPDs :many
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date, sequence_number FROM travel_records
WHERE deleted_at IS NULL
  AND spd_number = ANY($1::text[])
ORDER BY created_at DESC, id ASC
`

func (q *Queries) GetRecordsBySPDs(ctx context.Context, spds []string) ([]TravelRecord, error) {
	rows, err := q.db.QueryContext(ctx, getRecordsBySPDs, pq.Array(spds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelRecord{}
	for rows.Next() {
		var i TravelRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SpdNumber,
			&i.EmployeeID,
			&i.CreatorID,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.Province,
			&i.Type,
			&i.Purpose,
			&i.Stakeholder,
			&i.Agenda,
			&i.Status,
			&i.IsViewed,
			&i.TotalCost,
			&i.SuratTugasPath,
			&i.SuratTugasNumber,
			&i.SuratTugasDate,
			&i.SequenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSequenceNumbers = `-- name: GetSequenceNumbers :many
WITH ordered AS (
    SELECT id, ROW_NUMBER() OVER (
        ORDER BY CAST(SUBSTRING(spd_number FROM '[0-9]+') AS INTEGER) ASC, sequence_number ASC, created_at ASC
    ) as actual_rank 
    FROM travel_records 
    WHERE deleted_at IS NULL AND spd_number IS NOT NULL AND spd_number <> ''
)
SELECT id, actual_rank::int AS sequence_number 
FROM ordered 
WHERE id = ANY($1::uuid[])
`

type GetSequenceNumbersRow struct {
	ID             uuid.UUID `json:"id"`
	SequenceNumber int32     `json:"sequence_number"`
}

func (q *Queries) GetSequenceNumbers(ctx context.Context, recordIds []uuid.UUID) ([]GetSequenceNumbersRow, error) {
	rows, err := q.db.QueryContext(ctx, getSequenceNumbers, pq.Array(recordIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSequenceNumbersRow{}
	for rows.Next() {
		var i GetSequenceNumbersRow
		if err := rows.Scan(&i.ID, &i.SequenceNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalPaginatedSPDsCount = `-- name: GetTotalPaginatedSPDsCount :one
SELECT COUNT(DISTINCT travel_records.spd_number)
FROM travel_records
LEFT JOIN users ON travel_records.employee_id = users.id
WHERE travel_records.deleted_at IS NULL
  AND (NULLIF($1::text, '') IS NULL OR travel_records.status = $1)
  AND (
    NULLIF($2::text, '') IS NULL
    OR travel_records.spd_number ILIKE '%' || $2 || '%'
    OR travel_records.location ILIKE '%' || $2 || '%'
    OR users.name ILIKE '%' || $2 || '%'
  )
  AND (NULLIF($3::timestamp, NULL) IS NULL OR travel_records.start_date >= $3)
  AND (NULLIF($4::timestamp, NULL) IS NULL OR travel_records.start_date <= $4)
  AND (NULLIF($5::uuid, NULL) IS NULL OR travel_records.employee_id = $5 OR travel_records.creator_id = $5)
`

type GetTotalPaginatedSPDsCountParams struct {
	Status    sql.NullString `json:"status"`
	Search    sql.NullString `json:"search"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	UserID    uuid.NullUUID  `json:"user_id"`
}

func (q *Queries) GetTotalPaginatedSPDsCount(ctx context.Context, arg GetTotalPaginatedSPDsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPaginatedSPDsCount,
		arg.Status,
		arg.Search,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalTripsCount = `-- name: GetTotalTripsCount :one
SELECT COUNT(DISTINCT spd_number) 
FROM travel_records 
WHERE deleted_at IS NULL
  AND (NULLIF($1::uuid, NULL) IS NULL OR employee_id = $1 OR creator_id = $1)
`

func (q *Queries) GetTotalTripsCount(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalTripsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTravelCostByRecordID = `-- name: GetTravelCostByRecordID :one
SELECT travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs, details FROM travel_costs WHERE travel_record_id = $1 LIMIT 1
`

func (q *Queries) GetTravelCostByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelCost, error) {
	row := q.db.QueryRowContext(ctx, getTravelCostByRecordID, travelRecordID)
	var i TravelCost
	err := row.Scan(
		&i.TravelRecordID,
		&i.TicketGo,
		&i.TicketBack,
		&i.DailyAllowanceDays,
		&i.DailyAllowanceRate,
		&i.HotelDays,
		&i.HotelRate,
		&i.LocalTransport,
		&i.RegionalTransport,
		&i.TransportMode,
		&i.TransportAmount,
		&i.OtherCost,
		&i.OtherCostDesc,
		&i.ReceiptFiles,
		&i.TicketGoFile,
		&i.TicketBackFile,
		&i.BoardingPassFile,
		&i.HotelFile,
		&i.TransportFile,
		&i.AdditionalCosts,
		&i.Details,
	)
	return i, err
}

const getTravelCostsByRecordIDs = `-- name: GetTravelCostsByRecordIDs :many
SELECT travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs, details FROM travel_costs 
WHERE travel_record_id = ANY($1::uuid[])
`

func (q *Queries) GetTravelCostsByRecordIDs(ctx context.Context, recordIds []uuid.UUID) ([]TravelCost, error) {
	rows, err := q.db.QueryContext(ctx, getTravelCostsByRecordIDs, pq.Array(recordIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelCost{}
	for rows.Next() {
		var i TravelCost
		if err := rows.Scan(
			&i.TravelRecordID,
			&i.TicketGo,
			&i.TicketBack,
			&i.DailyAllowanceDays,
			&i.DailyAllowanceRate,
			&i.HotelDays,
			&i.HotelRate,
			&i.LocalTransport,
			&i.RegionalTransport,
			&i.TransportMode,
			&i.TransportAmount,
			&i.OtherCost,
			&i.OtherCostDesc,
			&i.ReceiptFiles,
			&i.TicketGoFile,
			&i.TicketBackFile,
			&i.BoardingPassFile,
			&i.HotelFile,
			&i.TransportFile,
			&i.AdditionalCosts,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelLocationsByRecordID = `-- name: GetTravelLocationsByRecordID :many
SELECT id, created_at, updated_at, deleted_at, travel_record_id, location, province, start_date, end_date FROM travel_locations WHERE travel_record_id = $1 AND deleted_at IS NULL ORDER BY start_date ASC, created_at ASC
`

func (q *Queries) GetTravelLocationsByRecordID(ctx context.Context, travelRecordID uuid.UUID) ([]TravelLocation, error) {
	rows, err := q.db.QueryContext(ctx, getTravelLocationsByRecordID, travelRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelLocation{}
	for rows.Next() {
		var i TravelLocation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TravelRecordID,
			&i.Location,
			&i.Province,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelLocationsByRecordIDs = `-- name: GetTravelLocationsByRecordIDs :many
SELECT id, created_at, updated_at, deleted_at, travel_record_id, location, province, start_date, end_date FROM travel_locations 
WHERE travel_record_id = ANY($1::uuid[]) 
  AND deleted_at IS NULL
`

func (q *Queries) GetTravelLocationsByRecordIDs(ctx context.Context, recordIds []uuid.UUID) ([]TravelLocation, error) {
	rows, err := q.db.QueryContext(ctx, getTravelLocationsByRecordIDs, pq.Array(recordIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelLocation{}
	for rows.Next() {
		var i TravelLocation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TravelRecordID,
			&i.Location,
			&i.Province,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelRecordByID = `-- name: GetTravelRecordByID :one
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date, sequence_number FROM travel_records WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTravelRecordByID(ctx context.Context, id uuid.UUID) (TravelRecord, error) {
	row := q.db.QueryRowContext(ctx, getTravelRecordByID, id)
	var i TravelRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.EmployeeID,
		&i.CreatorID,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.Province,
		&i.Type,
		&i.Purpose,
		&i.Stakeholder,
		&i.Agenda,
		&i.Status,
		&i.IsViewed,
		&i.TotalCost,
		&i.SuratTugasPath,
		&i.SuratTugasNumber,
		&i.SuratTugasDate,
		&i.SequenceNumber,
	)
	return i, err
}

const getTravelRecords = `-- name: GetTravelRecords :many
SELECT id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date, sequence_number FROM travel_records
WHERE deleted_at IS NULL
  AND (NULLIF($1::text, '') IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT 1000
`

func (q *Queries) GetTravelRecords(ctx context.Context, dollar_1 string) ([]TravelRecord, error) {
	rows, err := q.db.QueryContext(ctx, getTravelRecords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelRecord{}
	for rows.Next() {
		var i TravelRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SpdNumber,
			&i.EmployeeID,
			&i.CreatorID,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.Province,
			&i.Type,
			&i.Purpose,
			&i.Stakeholder,
			&i.Agenda,
			&i.Status,
			&i.IsViewed,
			&i.TotalCost,
			&i.SuratTugasPath,
			&i.SuratTugasNumber,
			&i.SuratTugasDate,
			&i.SequenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelReportByRecordID = `-- name: GetTravelReportByRecordID :one
SELECT travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file, ppk_name, ppk_nip, bendahara_name, bendahara_nip, tanggal_merah FROM travel_reports WHERE travel_record_id = $1 LIMIT 1
`

func (q *Queries) GetTravelReportByRecordID(ctx context.Context, travelRecordID uuid.UUID) (TravelReport, error) {
	row := q.db.QueryRowContext(ctx, getTravelReportByRecordID, travelRecordID)
	var i TravelReport
	err := row.Scan(
		&i.TravelRecordID,
		&i.Text,
		&i.SubmittedAt,
		&i.Files,
		&i.SppdFile,
		&i.SuratTugasFile,
		&i.PpkName,
		&i.PpkNip,
		&i.BendaharaName,
		&i.BendaharaNip,
		&i.TanggalMerah,
	)
	return i, err
}

const getTravelReportsByRecordIDs = `-- name: GetTravelReportsByRecordIDs :many
SELECT travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file, ppk_name, ppk_nip, bendahara_name, bendahara_nip, tanggal_merah FROM travel_reports 
WHERE travel_record_id = ANY($1::uuid[])
`

func (q *Queries) GetTravelReportsByRecordIDs(ctx context.Context, recordIds []uuid.UUID) ([]TravelReport, error) {
	rows, err := q.db.QueryContext(ctx, getTravelReportsByRecordIDs, pq.Array(recordIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TravelReport{}
	for rows.Next() {
		var i TravelReport
		if err := rows.Scan(
			&i.TravelRecordID,
			&i.Text,
			&i.SubmittedAt,
			&i.Files,
			&i.SppdFile,
			&i.SuratTugasFile,
			&i.PpkName,
			&i.PpkNip,
			&i.BendaharaName,
			&i.BendaharaNip,
			&i.TanggalMerah,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSpdNumber = `-- name: NextSpdNumber :one
SELECT nextval('spd_number_seq')::BIGINT AS next_val
`

// Returns the next unique sequence value for SPD number generation.
// nextval() is atomic and safe under concurrent load.
func (q *Queries) NextSpdNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSpdNumber)
	var next_val int64
	err := row.Scan(&next_val)
	return next_val, err
}

const syncSpdSequence = `-- name: SyncSpdSequence :exec
DO $$
DECLARE
    max_id bigint;
    has_records boolean;
BEGIN
    SELECT MAX(CAST(NULLIF(regexp_replace(spd_number, '\D', '', 'g'), '') AS BIGINT)) INTO max_id FROM travel_records WHERE spd_number ILIKE 'ID-SPJ-%' AND deleted_at IS NULL;
    SELECT COUNT(*) > 0 INTO has_records FROM travel_records WHERE deleted_at IS NULL;
    
    IF has_records THEN
        PERFORM setval('spd_number_seq', COALESCE(max_id, 1), true);
    ELSE
        PERFORM setval('spd_number_seq', 1, false);
    END IF;
END $$
`

func (q *Queries) SyncSpdSequence(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, syncSpdSequence)
	return err
}

const updateTravelCost = `-- name: UpdateTravelCost :one
UPDATE travel_costs SET
  ticket_go = $2, ticket_back = $3, daily_allowance_days = $4, daily_allowance_rate = $5, hotel_days = $6, hotel_rate = $7, local_transport = $8, regional_transport = $9, transport_mode = $10, transport_amount = $11, other_cost = $12, other_cost_desc = $13, receipt_files = $14, ticket_go_file = $15, ticket_back_file = $16, boarding_pass_file = $17, hotel_file = $18, transport_file = $19, additional_costs = $20, details = $21
WHERE travel_record_id = $1
RETURNING travel_record_id, ticket_go, ticket_back, daily_allowance_days, daily_allowance_rate, hotel_days, hotel_rate, local_transport, regional_transport, transport_mode, transport_amount, other_cost, other_cost_desc, receipt_files, ticket_go_file, ticket_back_file, boarding_pass_file, hotel_file, transport_file, additional_costs, details
`

type UpdateTravelCostParams struct {
	TravelRecordID     uuid.UUID             `json:"travel_record_id"`
	TicketGo           sql.NullFloat64       `json:"ticket_go"`
	TicketBack         sql.NullFloat64       `json:"ticket_back"`
	DailyAllowanceDays sql.NullInt32         `json:"daily_allowance_days"`
	DailyAllowanceRate sql.NullFloat64       `json:"daily_allowance_rate"`
	HotelDays          sql.NullInt32         `json:"hotel_days"`
	HotelRate          sql.NullFloat64       `json:"hotel_rate"`
	LocalTransport     sql.NullFloat64       `json:"local_transport"`
	RegionalTransport  sql.NullFloat64       `json:"regional_transport"`
	TransportMode      sql.NullString        `json:"transport_mode"`
	TransportAmount    sql.NullFloat64       `json:"transport_amount"`
	OtherCost          sql.NullFloat64       `json:"other_cost"`
	OtherCostDesc      sql.NullString        `json:"other_cost_desc"`
	ReceiptFiles       pqtype.NullRawMessage `json:"receipt_files"`
	TicketGoFile       pqtype.NullRawMessage `json:"ticket_go_file"`
	TicketBackFile     pqtype.NullRawMessage `json:"ticket_back_file"`
	BoardingPassFile   pqtype.NullRawMessage `json:"boarding_pass_file"`
	HotelFile          pqtype.NullRawMessage `json:"hotel_file"`
	TransportFile      pqtype.NullRawMessage `json:"transport_file"`
	AdditionalCosts    pqtype.NullRawMessage `json:"additional_costs"`
	Details            pqtype.NullRawMessage `json:"details"`
}

func (q *Queries) UpdateTravelCost(ctx context.Context, arg UpdateTravelCostParams) (TravelCost, error) {
	row := q.db.QueryRowContext(ctx, updateTravelCost,
		arg.TravelRecordID,
		arg.TicketGo,
		arg.TicketBack,
		arg.DailyAllowanceDays,
		arg.DailyAllowanceRate,
		arg.HotelDays,
		arg.HotelRate,
		arg.LocalTransport,
		arg.RegionalTransport,
		arg.TransportMode,
		arg.TransportAmount,
		arg.OtherCost,
		arg.OtherCostDesc,
		arg.ReceiptFiles,
		arg.TicketGoFile,
		arg.TicketBackFile,
		arg.BoardingPassFile,
		arg.HotelFile,
		arg.TransportFile,
		arg.AdditionalCosts,
		arg.Details,
	)
	var i TravelCost
	err := row.Scan(
		&i.TravelRecordID,
		&i.TicketGo,
		&i.TicketBack,
		&i.DailyAllowanceDays,
		&i.DailyAllowanceRate,
		&i.HotelDays,
		&i.HotelRate,
		&i.LocalTransport,
		&i.RegionalTransport,
		&i.TransportMode,
		&i.TransportAmount,
		&i.OtherCost,
		&i.OtherCostDesc,
		&i.ReceiptFiles,
		&i.TicketGoFile,
		&i.TicketBackFile,
		&i.BoardingPassFile,
		&i.HotelFile,
		&i.TransportFile,
		&i.AdditionalCosts,
		&i.Details,
	)
	return i, err
}

const updateTravelRecord = `-- name: UpdateTravelRecord :one
UPDATE travel_records SET
  spd_number = $2,
  employee_id = $3,
  creator_id = $4,
  start_date = $5,
  end_date = $6,
  location = $7,
  province = $8,
  type = $9,
  purpose = $10,
  stakeholder = $11,
  agenda = $12,
  status = $13,
  is_viewed = $14,
  total_cost = $15,
  surat_tugas_path = $16,
  surat_tugas_number = $17,
  surat_tugas_date = $18,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, spd_number, employee_id, creator_id, start_date, end_date, location, province, type, purpose, stakeholder, agenda, status, is_viewed, total_cost, surat_tugas_path, surat_tugas_number, surat_tugas_date, sequence_number
`

type UpdateTravelRecordParams struct {
	ID               uuid.UUID       `json:"id"`
	SpdNumber        sql.NullString  `json:"spd_number"`
	EmployeeID       uuid.UUID       `json:"employee_id"`
	CreatorID        uuid.UUID       `json:"creator_id"`
	StartDate        sql.NullTime    `json:"start_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	Location         sql.NullString  `json:"location"`
	Province         sql.NullString  `json:"province"`
	Type             sql.NullString  `json:"type"`
	Purpose          sql.NullString  `json:"purpose"`
	Stakeholder      sql.NullString  `json:"stakeholder"`
	Agenda           sql.NullString  `json:"agenda"`
	Status           sql.NullString  `json:"status"`
	IsViewed         sql.NullBool    `json:"is_viewed"`
	TotalCost        sql.NullFloat64 `json:"total_cost"`
	SuratTugasPath   sql.NullString  `json:"surat_tugas_path"`
	SuratTugasNumber sql.NullString  `json:"surat_tugas_number"`
	SuratTugasDate   sql.NullTime    `json:"surat_tugas_date"`
}

func (q *Queries) UpdateTravelRecord(ctx context.Context, arg UpdateTravelRecordParams) (TravelRecord, error) {
	row := q.db.QueryRowContext(ctx, updateTravelRecord,
		arg.ID,
		arg.SpdNumber,
		arg.EmployeeID,
		arg.CreatorID,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.Province,
		arg.Type,
		arg.Purpose,
		arg.Stakeholder,
		arg.Agenda,
		arg.Status,
		arg.IsViewed,
		arg.TotalCost,
		arg.SuratTugasPath,
		arg.SuratTugasNumber,
		arg.SuratTugasDate,
	)
	var i TravelRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SpdNumber,
		&i.EmployeeID,
		&i.CreatorID,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.Province,
		&i.Type,
		&i.Purpose,
		&i.Stakeholder,
		&i.Agenda,
		&i.Status,
		&i.IsViewed,
		&i.TotalCost,
		&i.SuratTugasPath,
		&i.SuratTugasNumber,
		&i.SuratTugasDate,
		&i.SequenceNumber,
	)
	return i, err
}

const updateTravelReport = `-- name: UpdateTravelReport :one
UPDATE travel_reports SET
  text = $2, submitted_at = $3, files = $4, sppd_file = $5, surat_tugas_file = $6, ppk_name = $7, ppk_nip = $8, bendahara_name = $9, bendahara_nip = $10, tanggal_merah = $11
WHERE travel_record_id = $1
RETURNING travel_record_id, text, submitted_at, files, sppd_file, surat_tugas_file, ppk_name, ppk_nip, bendahara_name, bendahara_nip, tanggal_merah
`

type UpdateTravelReportParams struct {
	TravelRecordID uuid.UUID             `json:"travel_record_id"`
	Text           sql.NullString        `json:"text"`
	SubmittedAt    sql.NullTime          `json:"submitted_at"`
	Files          pqtype.NullRawMessage `json:"files"`
	SppdFile       pqtype.NullRawMessage `json:"sppd_file"`
	SuratTugasFile pqtype.NullRawMessage `json:"surat_tugas_file"`
	PpkName        sql.NullString        `json:"ppk_name"`
	PpkNip         sql.NullString        `json:"ppk_nip"`
	BendaharaName  sql.NullString        `json:"bendahara_name"`
	BendaharaNip   sql.NullString        `json:"bendahara_nip"`
	TanggalMerah   pqtype.NullRawMessage `json:"tanggal_merah"`
}

func (q *Queries) UpdateTravelReport(ctx context.Context, arg UpdateTravelReportParams) (TravelReport, error) {
	row := q.db.QueryRowContext(ctx, updateTravelReport,
		arg.TravelRecordID,
		arg.Text,
		arg.SubmittedAt,
		arg.Files,
		arg.SppdFile,
		arg.SuratTugasFile,
		arg.PpkName,
		arg.PpkNip,
		arg.BendaharaName,
		arg.BendaharaNip,
		arg.TanggalMerah,
	)
	var i TravelReport
	err := row.Scan(
		&i.TravelRecordID,
		&i.Text,
		&i.SubmittedAt,
		&i.Files,
		&i.SppdFile,
		&i.SuratTugasFile,
		&i.PpkName,
		&i.PpkNip,
		&i.BendaharaName,
		&i.BendaharaNip,
		&i.TanggalMerah,
	)
	return i, err
}
