// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, password, name, role, nip, nomor_hp, pangkat, golongan, jabatan, tingkat_biaya, session_id, demo_password
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, created_at, updated_at, deleted_at, email, password, name, role, nip, nomor_hp, pangkat, golongan, jabatan, tingkat_biaya, session_id, demo_password
`

type CreateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Nip          sql.NullString `json:"nip"`
	NomorHp      sql.NullString `json:"nomor_hp"`
	Pangkat      sql.NullString `json:"pangkat"`
	Golongan     sql.NullString `json:"golongan"`
	Jabatan      sql.NullString `json:"jabatan"`
	TingkatBiaya sql.NullString `json:"tingkat_biaya"`
	SessionID    sql.NullString `json:"session_id"`
	DemoPassword sql.NullString `json:"demo_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Role,
		arg.Nip,
		arg.NomorHp,
		arg.Pangkat,
		arg.Golongan,
		arg.Jabatan,
		arg.TingkatBiaya,
		arg.SessionID,
		arg.DemoPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.Nip,
		&i.NomorHp,
		&i.Pangkat,
		&i.Golongan,
		&i.Jabatan,
		&i.TingkatBiaya,
		&i.SessionID,
		&i.DemoPassword,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, deleted_at, email, password, name, role, nip, nomor_hp, pangkat, golongan, jabatan, tingkat_biaya, session_id, demo_password FROM users WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.Nip,
		&i.NomorHp,
		&i.Pangkat,
		&i.Golongan,
		&i.Jabatan,
		&i.TingkatBiaya,
		&i.SessionID,
		&i.DemoPassword,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, deleted_at, email, password, name, role, nip, nomor_hp, pangkat, golongan, jabatan, tingkat_biaya, session_id, demo_password FROM users WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.Nip,
		&i.NomorHp,
		&i.Pangkat,
		&i.Golongan,
		&i.Jabatan,
		&i.TingkatBiaya,
		&i.SessionID,
		&i.DemoPassword,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, created_at, updated_at, deleted_at, email, password, name, role, nip, nomor_hp, pangkat, golongan, jabatan, tingkat_biaya, session_id, demo_password FROM users WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Email,
			&i.Password,
			&i.Name,
			&i.Role,
			&i.Nip,
			&i.NomorHp,
			&i.Pangkat,
			&i.Golongan,
			&i.Jabatan,
			&i.TingkatBiaya,
			&i.SessionID,
			&i.DemoPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, created_at, updated_at, deleted_at, email, password, name, role, nip, nomor_hp, pangkat, golongan, jabatan, tingkat_biaya, session_id, demo_password FROM users WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Email,
			&i.Password,
			&i.Name,
			&i.Role,
			&i.Nip,
			&i.NomorHp,
			&i.Pangkat,
			&i.Golongan,
			&i.Jabatan,
			&i.TingkatBiaya,
			&i.SessionID,
			&i.DemoPassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  email = $2,
  password = $3,
  name = $4,
  role = $5,
  nip = $6,
  nomor_hp = $7,
  pangkat = $8,
  golongan = $9,
  jabatan = $10,
  tingkat_biaya = $11,
  session_id = $12,
  demo_password = $13,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, email, password, name, role, nip, nomor_hp, pangkat, golongan, jabatan, tingkat_biaya, session_id, demo_password
`

type UpdateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Nip          sql.NullString `json:"nip"`
	NomorHp      sql.NullString `json:"nomor_hp"`
	Pangkat      sql.NullString `json:"pangkat"`
	Golongan     sql.NullString `json:"golongan"`
	Jabatan      sql.NullString `json:"jabatan"`
	TingkatBiaya sql.NullString `json:"tingkat_biaya"`
	SessionID    sql.NullString `json:"session_id"`
	DemoPassword sql.NullString `json:"demo_password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Role,
		arg.Nip,
		arg.NomorHp,
		arg.Pangkat,
		arg.Golongan,
		arg.Jabatan,
		arg.TingkatBiaya,
		arg.SessionID,
		arg.DemoPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.Nip,
		&i.NomorHp,
		&i.Pangkat,
		&i.Golongan,
		&i.Jabatan,
		&i.TingkatBiaya,
		&i.SessionID,
		&i.DemoPassword,
	)
	return i, err
}
